// Auto-generated by: pnpm --filter @flowos/db gen:types
// Run after applying Supabase migrations to regenerate.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          org_id: string | null;
          display_name: string | null;
          avatar_url: string | null;
          tier: "free" | "pro" | "builder" | "unlimited";
          plan_expires_at: string | null;
          bonus_runs: number;
          is_beta_tester: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          org_id?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          tier?: "free" | "pro" | "builder" | "unlimited";
          plan_expires_at?: string | null;
          bonus_runs?: number;
          is_beta_tester?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          tier?: "free" | "pro" | "builder" | "unlimited";
          plan_expires_at?: string | null;
          bonus_runs?: number;
          is_beta_tester?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      redemption_codes: {
        Row: {
          id: string;
          code: string;
          label: string | null;
          type: "pro_lifetime" | "builder_lifetime" | "unlimited" | "pro_trial" | "run_credits";
          value: Json | null;
          locked_to_email: string | null;
          max_uses: number | null;
          uses_count: number;
          expires_at: string | null;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          label?: string | null;
          type: "pro_lifetime" | "builder_lifetime" | "unlimited" | "pro_trial" | "run_credits";
          value?: Json | null;
          locked_to_email?: string | null;
          max_uses?: number | null;
          uses_count?: number;
          expires_at?: string | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          label?: string | null;
          type?: "pro_lifetime" | "builder_lifetime" | "unlimited" | "pro_trial" | "run_credits";
          value?: Json | null;
          locked_to_email?: string | null;
          max_uses?: number | null;
          uses_count?: number;
          expires_at?: string | null;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
        };
      };
      redemptions: {
        Row: {
          id: string;
          code_id: string;
          user_id: string;
          redeemed_at: string;
        };
        Insert: {
          id?: string;
          code_id: string;
          user_id: string;
          redeemed_at?: string;
        };
        Update: {
          id?: string;
          code_id?: string;
          user_id?: string;
          redeemed_at?: string;
        };
      };
      app_logs: {
        Row: {
          id: string;
          user_id: string;
          org_id: string | null;
          program_id: string | null;
          run_id: string | null;
          level: "info" | "warning" | "error";
          source: string;
          event: string;
          status: string;
          message: string;
          details: Json | null;
          duration_ms: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          org_id?: string | null;
          program_id?: string | null;
          run_id?: string | null;
          level: "info" | "warning" | "error";
          source: string;
          event: string;
          status: string;
          message: string;
          details?: Json | null;
          duration_ms?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          org_id?: string | null;
          program_id?: string | null;
          run_id?: string | null;
          level?: "info" | "warning" | "error";
          source?: string;
          event?: string;
          status?: string;
          message?: string;
          details?: Json | null;
          duration_ms?: number | null;
          created_at?: string;
        };
      };
      data_retention_audit: {
        Row: {
          id: string;
          job_name: string;
          cleared_run_payloads: number;
          cleared_node_input_payloads: number;
          cleared_node_output_payloads: number;
          deleted_runs: number;
          deleted_audit_rows: number;
          details: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          job_name: string;
          cleared_run_payloads?: number;
          cleared_node_input_payloads?: number;
          cleared_node_output_payloads?: number;
          deleted_runs?: number;
          deleted_audit_rows?: number;
          details?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          job_name?: string;
          cleared_run_payloads?: number;
          cleared_node_input_payloads?: number;
          cleared_node_output_payloads?: number;
          deleted_runs?: number;
          deleted_audit_rows?: number;
          details?: Json | null;
          created_at?: string;
        };
      };
      data_subject_requests: {
        Row: {
          id: string;
          user_id: string;
          org_id: string | null;
          request_type: "access" | "rectification" | "erasure" | "restriction" | "portability" | "objection" | "withdrawal";
          status: "submitted" | "in_review" | "waiting_on_user" | "completed" | "rejected";
          requester_email: string | null;
          details: string | null;
          response_summary: string | null;
          submitted_at: string;
          due_at: string;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          org_id?: string | null;
          request_type: "access" | "rectification" | "erasure" | "restriction" | "portability" | "objection" | "withdrawal";
          status?: "submitted" | "in_review" | "waiting_on_user" | "completed" | "rejected";
          requester_email?: string | null;
          details?: string | null;
          response_summary?: string | null;
          submitted_at?: string;
          due_at?: string;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          org_id?: string | null;
          request_type?: "access" | "rectification" | "erasure" | "restriction" | "portability" | "objection" | "withdrawal";
          status?: "submitted" | "in_review" | "waiting_on_user" | "completed" | "rejected";
          requester_email?: string | null;
          details?: string | null;
          response_summary?: string | null;
          submitted_at?: string;
          due_at?: string;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      connection_webhook_secrets: {
        Row: {
          id: string;
          connection_id: string;
          provider: string;
          secret_name: string;
          vault_secret_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          connection_id: string;
          provider: string;
          secret_name: string;
          vault_secret_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          connection_id?: string;
          provider?: string;
          secret_name?: string;
          vault_secret_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      oauth_state_nonces: {
        Row: {
          flow_id: string;
          user_id: string;
          nonce_hash: string;
          issued_at: string;
          expires_at: string;
          consumed_at: string | null;
          created_at: string;
        };
        Insert: {
          flow_id: string;
          user_id: string;
          nonce_hash: string;
          issued_at?: string;
          expires_at: string;
          consumed_at?: string | null;
          created_at?: string;
        };
        Update: {
          flow_id?: string;
          user_id?: string;
          nonce_hash?: string;
          issued_at?: string;
          expires_at?: string;
          consumed_at?: string | null;
          created_at?: string;
        };
      };
      webhook_deliveries: {
        Row: {
          source: string;
          delivery_id: string;
          first_seen_at: string;
          expires_at: string;
        };
        Insert: {
          source: string;
          delivery_id: string;
          first_seen_at?: string;
          expires_at: string;
        };
        Update: {
          source?: string;
          delivery_id?: string;
          first_seen_at?: string;
          expires_at?: string;
        };
      };
      api_keys: {
        Row: {
          id: string;
          user_id: string;
          org_id: string | null;
          name: string;
          provider: string;
          vault_secret_id: string;
          is_valid: boolean;
          last_validated_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          org_id?: string | null;
          name: string;
          provider: string;
          vault_secret_id: string;
          is_valid?: boolean;
          last_validated_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          org_id?: string | null;
          name?: string;
          provider?: string;
          vault_secret_id?: string;
          is_valid?: boolean;
          last_validated_at?: string | null;
          created_at?: string;
        };
      };
      connections: {
        Row: {
          id: string;
          user_id: string;
          org_id: string | null;
          name: string;
          provider: string;
          auth_type: "oauth" | "api_key";
          vault_secret_id: string;
          scopes: string[] | null;
          metadata: Json | null;
          is_valid: boolean;
          last_validated_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          org_id?: string | null;
          name: string;
          provider: string;
          auth_type: "oauth" | "api_key";
          vault_secret_id: string;
          scopes?: string[] | null;
          metadata?: Json | null;
          is_valid?: boolean;
          last_validated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          org_id?: string | null;
          name?: string;
          provider?: string;
          auth_type?: "oauth" | "api_key";
          vault_secret_id?: string;
          scopes?: string[] | null;
          metadata?: Json | null;
          is_valid?: boolean;
          last_validated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      programs: {
        Row: {
          id: string;
          user_id: string;
          org_id: string | null;
          name: string;
          description: string | null;
          schema: Json;
          schema_version: number;
          execution_mode: "autonomous" | "supervised" | "manual";
          is_active: boolean;
          conflict_policy: "queue" | "skip" | "fail";
          last_run_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          org_id?: string | null;
          name: string;
          description?: string | null;
          schema: Json;
          schema_version?: number;
          execution_mode?: "autonomous" | "supervised" | "manual";
          is_active?: boolean;
          conflict_policy?: "queue" | "skip" | "fail";
          last_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          org_id?: string | null;
          name?: string;
          description?: string | null;
          schema?: Json;
          schema_version?: number;
          execution_mode?: "autonomous" | "supervised" | "manual";
          is_active?: boolean;
          conflict_policy?: "queue" | "skip" | "fail";
          last_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      program_connections: {
        Row: { program_id: string; connection_id: string };
        Insert: { program_id: string; connection_id: string };
        Update: { program_id?: string; connection_id?: string };
      };
      program_versions: {
        Row: {
          id: string;
          program_id: string;
          version: number;
          schema: Json;
          change_summary: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          program_id: string;
          version: number;
          schema: Json;
          change_summary?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          program_id?: string;
          version?: number;
          schema?: Json;
          change_summary?: string | null;
          created_at?: string;
        };
      };
      runs: {
        Row: {
          id: string;
          program_id: string;
          triggered_by: string;
          trigger_payload: Json | null;
          status: "pending" | "running" | "paused" | "completed" | "failed" | "cancelled";
          started_at: string | null;
          completed_at: string | null;
          error_message: string | null;
          prompt_tokens: number;
          completion_tokens: number;
          total_tokens: number;
          estimated_cost_usd: number;
          connector_api_calls: number;
          model_call_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          program_id: string;
          triggered_by: string;
          trigger_payload?: Json | null;
          status?: "pending" | "running" | "paused" | "completed" | "failed" | "cancelled";
          started_at?: string | null;
          completed_at?: string | null;
          error_message?: string | null;
          prompt_tokens?: number;
          completion_tokens?: number;
          total_tokens?: number;
          estimated_cost_usd?: number;
          connector_api_calls?: number;
          model_call_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          program_id?: string;
          triggered_by?: string;
          trigger_payload?: Json | null;
          status?: "pending" | "running" | "paused" | "completed" | "failed" | "cancelled";
          started_at?: string | null;
          completed_at?: string | null;
          error_message?: string | null;
          prompt_tokens?: number;
          completion_tokens?: number;
          total_tokens?: number;
          estimated_cost_usd?: number;
          connector_api_calls?: number;
          model_call_count?: number;
          created_at?: string;
        };
      };
      node_executions: {
        Row: {
          id: string;
          run_id: string;
          node_id: string;
          status:
            | "pending"
            | "queued"
            | "running"
            | "waiting_approval"
            | "completed"
            | "failed"
            | "skipped";
          input_payload: Json | null;
          output_payload: Json | null;
          error_message: string | null;
          retry_count: number;
          started_at: string | null;
          completed_at: string | null;
          prompt_tokens: number;
          completion_tokens: number;
          total_tokens: number;
          estimated_cost_usd: number;
          connector_api_calls: number;
          model_call_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          run_id: string;
          node_id: string;
          status?:
            | "pending"
            | "queued"
            | "running"
            | "waiting_approval"
            | "completed"
            | "failed"
            | "skipped";
          input_payload?: Json | null;
          output_payload?: Json | null;
          error_message?: string | null;
          retry_count?: number;
          started_at?: string | null;
          completed_at?: string | null;
          prompt_tokens?: number;
          completion_tokens?: number;
          total_tokens?: number;
          estimated_cost_usd?: number;
          connector_api_calls?: number;
          model_call_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          run_id?: string;
          node_id?: string;
          status?:
            | "pending"
            | "queued"
            | "running"
            | "waiting_approval"
            | "completed"
            | "failed"
            | "skipped";
          input_payload?: Json | null;
          output_payload?: Json | null;
          error_message?: string | null;
          retry_count?: number;
          started_at?: string | null;
          completed_at?: string | null;
          prompt_tokens?: number;
          completion_tokens?: number;
          total_tokens?: number;
          estimated_cost_usd?: number;
          connector_api_calls?: number;
          model_call_count?: number;
          created_at?: string;
        };
      };
      approvals: {
        Row: {
          id: string;
          node_execution_id: string;
          user_id: string;
          status: "pending" | "approved" | "rejected";
          context: Json | null;
          decision_note: string | null;
          decided_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          node_execution_id: string;
          user_id: string;
          status?: "pending" | "approved" | "rejected";
          context?: Json | null;
          decision_note?: string | null;
          decided_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          node_execution_id?: string;
          user_id?: string;
          status?: "pending" | "approved" | "rejected";
          context?: Json | null;
          decision_note?: string | null;
          decided_at?: string | null;
          created_at?: string;
        };
      };
      triggers: {
        Row: {
          id: string;
          program_id: string;
          type: "manual" | "cron" | "webhook" | "event" | "program";
          config: Json;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          program_id: string;
          type: "manual" | "cron" | "webhook" | "event" | "program";
          config: Json;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          program_id?: string;
          type?: "manual" | "cron" | "webhook" | "event" | "program";
          config?: Json;
          is_active?: boolean;
          created_at?: string;
        };
      };
      usage: {
        Row: {
          id: string;
          user_id: string;
          org_id: string | null;
          period_start: string;
          period_end: string;
          program_count: number;
          execution_count: number;
          connection_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          org_id?: string | null;
          period_start: string;
          period_end: string;
          program_count?: number;
          execution_count?: number;
          connection_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          org_id?: string | null;
          period_start?: string;
          period_end?: string;
          program_count?: number;
          execution_count?: number;
          connection_count?: number;
          created_at?: string;
        };
      };
      resource_locks: {
        Row: {
          id: string;
          resource_type: string;
          resource_id: string;
          locked_by_run_id: string | null;
          acquired_at: string;
          expires_at: string;
        };
        Insert: {
          id?: string;
          resource_type: string;
          resource_id: string;
          locked_by_run_id?: string | null;
          acquired_at?: string;
          expires_at: string;
        };
        Update: {
          id?: string;
          resource_type?: string;
          resource_id?: string;
          locked_by_run_id?: string | null;
          acquired_at?: string;
          expires_at?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: {
      purge_expired_operational_data: {
        Args: {
          p_payload_retention?: string;
          p_run_retention?: string;
          p_audit_retention?: string;
        };
        Returns: Json;
      };
    };
    Enums: Record<string, never>;
  };
}
