#!/usr/bin/env python3
"""
Codegen script for apps/runtime.

Reads packages/schema/generated/schema.json (generated by @flowos/schema#codegen)
and emits apps/runtime/generated/models.py with Pydantic models via datamodel-code-generator.

Run from repo root: python apps/runtime/scripts/codegen.py
Or via turbo: pnpm codegen
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
SCHEMA_JSON = REPO_ROOT / "packages" / "schema" / "generated" / "schema.json"
OUT_DIR = REPO_ROOT / "apps" / "runtime" / "generated"
OUT_FILE = OUT_DIR / "models.py"


def main() -> int:
    if not SCHEMA_JSON.exists():
        print(f"[codegen] ERROR: Schema not found at {SCHEMA_JSON}", file=sys.stderr)
        print("[codegen] Run 'pnpm --filter @flowos/schema codegen' first", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Load and validate schema.json
    try:
        schema = json.loads(SCHEMA_JSON.read_text())
        defs = schema.get("definitions", {})
        if not defs:
            print(f"[codegen] WARNING: No definitions found in {SCHEMA_JSON}", file=sys.stderr)
        else:
            print(f"[codegen] Found {len(defs)} definitions in schema.json")
    except json.JSONDecodeError as e:
        print(f"[codegen] ERROR: Invalid JSON in {SCHEMA_JSON}: {e}", file=sys.stderr)
        return 1

    # Run datamodel-code-generator
    cmd = [
        sys.executable,
        "-m",
        "datamodel_code_generator",
        "--input",
        str(SCHEMA_JSON),
        "--input-file-type",
        "jsonschema",
        "--output",
        str(OUT_FILE),
        "--output-model-type",
        "pydantic_v2.BaseModel",
        "--field-constraints",
        "--use-standard-collections",
        "--use-generic-container-types",
        "--enable-faux-immutability",
        "--disable-timestamp",
        "--class-name",
        "ProgramSchema",
        "--use-schema-description",
        "--use-title-as-name",
        "--use-field-description",
        "--use-default",
        "--use-default-kwarg",
        "--no-allow-population-by-field-name",
        "--field-constraints",
    ]

    print(f"[codegen] Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=REPO_ROOT)

    if result.returncode != 0:
        print(f"[codegen] ERROR: datamodel-code-generator failed:", file=sys.stderr)
        print(result.stdout, file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        return result.returncode

    print(f"[codegen] Generated {OUT_FILE}")

    # Post-process: add header comment and fix imports
    content = OUT_FILE.read_text()
    header = (
        "# AUTO-GENERATED by apps/runtime/scripts/codegen.py — DO NOT EDIT BY HAND\n"
        "# Source: packages/schema/generated/schema.json\n"
        "# Generated via: datamodel-code-generator (pydantic_v2.BaseModel)\n"
        "# Run: python apps/runtime/scripts/codegen.py\n\n"
    )
    if not content.startswith("# AUTO-GENERATED"):
        content = header + content
        OUT_FILE.write_text(content)
        print(f"[codegen] Added header comment")

    return 0


if __name__ == "__main__":
    sys.exit(main())