// ─── corelyx connector init ─────────────────────────────────────────────────
// Scaffolds a new connector from a template with typed operations.

import * as fs from "node:fs";
import * as path from "node:path";

interface InitArgs {
  directory?: string;
  provider?: string;
  auth_type?: string;
  help?: boolean;
}

function parseArgs(args: string[]): InitArgs {
  const parsed: InitArgs = {};
  for (let i = 2; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--directory" || arg === "-d") {
      parsed.directory = args[++i];
    } else if (arg === "--provider" || arg === "-p") {
      parsed.provider = args[++i];
    } else if (arg === "--auth-type" || arg === "-a") {
      parsed.auth_type = args[++i];
    } else if (arg === "--help" || arg === "-h") {
      parsed.help = true;
    }
  }
  return parsed;
}

const INIT_HELP = `
Usage: corelyx connector init [options]

Options:
  --provider, -p    Provider slug (e.g. "myapi") [required]
  --directory, -d   Directory to create the connector in [default: ./connectors/custom/<provider>]
  --auth-type, -a   Auth type: oauth2, api_key, bearer, none [default: bearer]
  --help, -h        Show this help message

Example:
  corelyx connector init --provider myapi --auth-type bearer
`;

function generateAuthConfig(authType: string, provider: string): string {
  switch (authType) {
    case "oauth2":
      return `{
    type: "oauth2",
    authorization_url: "https://api.${provider}.com/oauth/authorize",
    token_url: "https://api.${provider}.com/oauth/token",
    scopes: ["read", "write"],
  }`;
    case "api_key":
      return `{
    type: "api_key",
    header: "X-API-Key",
  }`;
    case "none":
      return `{
    type: "none",
  }`;
    case "bearer":
    default:
      return `{
    type: "bearer",
    header: "Authorization",
    prefix: "Bearer",
  }`;
  }
}

function generateConnectorTemplate(provider: string, authType: string): string {
  const displayName = provider
    .split(/[_-]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

  return `// ${displayName} Connector
// Generated by @flowos/connector-kit

import { defineConnector, buildAuthHeaders } from "@flowos/connector-kit";
import { z } from "zod";

// ─── Input/Output Schemas ───────────────────────────────────────────────────

const listItemsInput = z.object({
  query: z.string().optional().describe("Search query filter"),
  limit: z.number().int().min(1).max(100).default(10).describe("Max items to return"),
});

const listItemsOutput = z.object({
  items: z.array(z.record(z.unknown())).describe("List of items"),
  total: z.number().describe("Total count"),
  has_more: z.boolean().describe("Whether more results exist"),
});

const getItemInput = z.object({
  item_id: z.string().describe("The item ID to fetch"),
});

const getItemOutput = z.object({
  item: z.record(z.unknown()).describe("The item details"),
});

// ─── Connector Definition ───────────────────────────────────────────────────

export const ${provider}Connector = defineConnector({
  provider: "${provider}",
  display_name: "${displayName}",
  description: "Connect to ${displayName} API",
  base_url: "https://api.${provider}.com/v1",
  auth: ${generateAuthConfig(authType, provider)},
  default_headers: {
    "Accept": "application/json",
  },
  operations: [
    {
      name: "list_items",
      description: "List items from ${displayName}",
      input: listItemsInput,
      output: listItemsOutput,
      execute: async (input, ctx) => {
        const params = new URLSearchParams();
        if (input.query) params.set("q", input.query);
        params.set("limit", String(input.limit));

        const headers = {
          ...ctx.default_headers,
          ...buildAuthHeaders(ctx.auth, ctx.auth.access_token ?? ""),
        };

        const response = await fetch(\`\${ctx.base_url}/items?\${params}\`, { headers });

        if (!response.ok) {
          throw new Error(\`\${displayName} API error: \${response.status} \${response.statusText}\`);
        }

        const data = await response.json();
        return {
          items: data.items ?? [],
          total: data.total ?? 0,
          has_more: data.has_more ?? false,
        };
      },
    },
    {
      name: "get_item",
      description: "Get a single item by ID",
      input: getItemInput,
      output: getItemOutput,
      execute: async (input, ctx) => {
        const headers = {
          ...ctx.default_headers,
          ...buildAuthHeaders(ctx.auth, ctx.auth.access_token ?? ""),
        };

        const response = await fetch(\`\${ctx.base_url}/items/\${input.item_id}\`, { headers });

        if (!response.ok) {
          throw new Error(\`\${displayName} API error: \${response.status} \${response.statusText}\`);
        }

        const data = await response.json();
        return { item: data };
      },
    },
  ],
});

export default ${provider}Connector;
`;
}

function generateTestTemplate(provider: string): string {
  return `// ${provider} Connector Tests
// Generated by @flowos/connector-kit

import { describe, it, expect } from "vitest";
import { ${provider}Connector } from "./index.js";

describe("${provider}Connector", () => {
  it("has correct provider name", () => {
    expect(${provider}Connector.provider).toBe("${provider}");
  });

  it("has required properties", () => {
    expect(${provider}Connector.display_name).toBeTruthy();
    expect(${provider}Connector.auth).toBeDefined();
    expect(${provider}Connector.operations.length).toBeGreaterThan(0);
  });

  it("has valid operation schemas", () => {
    for (const op of ${provider}Connector.operations) {
      expect(op.name).toMatch(/^[a-z][a-z0-9_]*$/);
      expect(op.description).toBeTruthy();
      expect(op.input).toBeDefined();
      expect(op.output).toBeDefined();
      expect(typeof op.execute).toBe("function");
    }
  });

  it("validates input schema for list_items", () => {
    const op = ${provider}Connector.operations.find((o) => o.name === "list_items");
    expect(op).toBeDefined();

    // Should accept valid input
    const validInput = { query: "test", limit: 5 };
    expect(() => op!.input.parse(validInput)).not.toThrow();

    // Should apply defaults
    const minimalInput = {};
    const parsed = op!.input.parse(minimalInput);
    expect(parsed.limit).toBe(10);
  });

  it("validates output schema", () => {
    const op = ${provider}Connector.operations.find((o) => o.name === "list_items");
    expect(op).toBeDefined();

    const validOutput = {
      items: [{ id: "1", name: "Test" }],
      total: 1,
      has_more: false,
    };
    expect(() => op!.output.parse(validOutput)).not.toThrow();
  });
});
`;
}

function generateReadme(provider: string): string {
  const displayName = provider
    .split(/[_-]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");

  return `# ${displayName} Connector

Custom connector for ${displayName}, built with @flowos/connector-kit.

## Setup

1. Install dependencies:
   \`\`\`bash
   pnpm install
   \`\`\`

2. Configure authentication:
   - **Bearer Token**: Set the \`access_token\` in your Corelyx connection settings
   - **API Key**: Set the \`api_key\` in your Corelyx connection settings

## Operations

| Operation | Description | Input | Output |
|-----------|-------------|-------|--------|
| \`list_items\` | List items from ${displayName} | \`query?\`, \`limit\` | \`items\`, \`total\`, \`has_more\` |
| \`get_item\` | Get a single item by ID | \`item_id\` | \`item\` |

## Development

### Add a new operation

1. Add the input/output Zod schemas in \`index.ts\`
2. Add the operation to the \`operations\` array in the connector definition
3. Run \`corelyx connector build\` to update the manifest
4. Run \`corelyx connector test\` to verify

### Test locally

\`\`\`bash
# Run tests
corelyx connector test --provider ${provider}

# Build manifest
corelyx connector build --directory .
\`\`\`

## Manifest Integration

After building, this connector will be included in \`connectors.manifest.json\`
and automatically available in the Corelyx editor palette and Genesis prompt builder.
`;
}

export async function runInit(args: string[]): Promise<void> {
  const parsed = parseArgs(args);

  if (parsed.help) {
    console.log(INIT_HELP);
    return;
  }

  if (!parsed.provider) {
    console.error("Error: --provider is required\n");
    console.log(INIT_HELP);
    process.exit(1);
  }

  const provider = parsed.provider.toLowerCase().replace(/[^a-z0-9_-]/g, "_");
  const authType = parsed.auth_type ?? "bearer";
  const directory = parsed.directory ?? path.join("connectors", "custom", provider);

  // Validate auth type
  if (!["oauth2", "api_key", "bearer", "none"].includes(authType)) {
    console.error(`Error: Invalid auth type "${authType}". Must be one of: oauth2, api_key, bearer, none`);
    process.exit(1);
  }

  // Check if directory already exists
  if (fs.existsSync(directory)) {
    console.error(`Error: Directory "${directory}" already exists. Use a different name or remove it first.`);
    process.exit(1);
  }

  // Create directory structure
  fs.mkdirSync(directory, { recursive: true });

  // Generate files
  const connectorCode = generateConnectorTemplate(provider, authType);
  const testCode = generateTestTemplate(provider);
  const readme = generateReadme(provider);

  fs.writeFileSync(path.join(directory, "index.ts"), connectorCode);
  fs.writeFileSync(path.join(directory, "index.test.ts"), testCode);
  fs.writeFileSync(path.join(directory, "README.md"), readme);

  console.log(`✓ Created connector: ${provider}`);
  console.log(`  Directory: ${directory}`);
  console.log(`  Auth type: ${authType}`);
  console.log(`  Files:`);
  console.log(`    - index.ts (connector definition)`);
  console.log(`    - index.test.ts (tests)`);
  console.log(`    - README.md (documentation)`);
  console.log();
  console.log("Next steps:");
  console.log(`  1. Edit ${directory}/index.ts to customize your connector`);
  console.log(`  2. Run: corelyx connector build --directory ${directory}`);
  console.log(`  3. Run: corelyx connector test --provider ${provider}`);
}
