/**
 * Connector Manifest — Dynamic loader for the generated connector manifest.
 *
 * The manifest is generated by apps/runtime/scripts/generate_connector_manifest.py
 * and provides a machine-readable list of all connector operations for:
 * - Genesis prompt builder (replaces hardcoded CONNECTOR_DEFINITIONS)
 * - Editor autocomplete (type-ahead search when adding nodes)
 * - Type-safe connector discovery
 *
 * Falls back to hardcoded CONNECTOR_DEFINITIONS when manifest is unavailable.
 */

// ConnectorDef type defined locally to avoid circular dependency with prompt.ts
// (prompt.ts imports from this module)
type ConnectorDef = {
  tier: 1 | 2 | 3;
  full?: string;
  medium?: string;
  stub?: string;
  gapReference?: string;
};

// We import CONNECTOR_DEFINITIONS dynamically to avoid circular deps
// At runtime, prompt.ts will have loaded by the time this is called
let _CONNECTOR_DEFINITIONS: Record<string, ConnectorDef> | null = null;

async function getConnectorDefinitions(): Promise<Record<string, ConnectorDef>> {
  if (_CONNECTOR_DEFINITIONS) return _CONNECTOR_DEFINITIONS;
  const mod = await import("./prompt");
  _CONNECTOR_DEFINITIONS = mod.CONNECTOR_DEFINITIONS as Record<string, ConnectorDef>;
  return _CONNECTOR_DEFINITIONS;
}

// ─── Types ──────────────────────────────────────────────────────────────────

export interface ConnectorManifestOperation {
  name: string;
  description: string;
  parameters: Array<{
    name: string;
    type?: string;
  }>;
}

export interface ConnectorManifestEntry {
  operations: ConnectorManifestOperation[];
  operation_count: number;
}

export interface ConnectorManifest {
  version: string;
  generated_at: string;
  connector_count: number;
  connectors: Record<string, ConnectorManifestEntry>;
}

export interface SearchResult {
  provider: string;
  operation: string;
  description: string;
  tier: 1 | 2 | 3;
}

// ─── Manifest Loader ────────────────────────────────────────────────────────

let cachedManifest: ConnectorManifest | null = null;

/**
 * Load the connector manifest from the generated JSON file.
 * Caches the result after first load.
 * Returns null if the manifest is not available (falls back to hardcoded defs).
 */
export async function loadConnectorManifest(): Promise<ConnectorManifest | null> {
  if (cachedManifest) return cachedManifest;

  try {
    const response = await fetch("/connectors.manifest.json");
    if (!response.ok) return null;
    const manifest: ConnectorManifest = await response.json();
    cachedManifest = manifest;
    return manifest;
  } catch {
    return null;
  }
}

/**
 * Synchronous manifest loader using dynamic import.
 * For use in server components or build-time.
 */
export function getManifestSync(): ConnectorManifest | null {
  return cachedManifest;
}

/**
 * Set the manifest directly (for testing or pre-loaded manifests).
 */
export function setManifest(manifest: ConnectorManifest): void {
  cachedManifest = manifest;
}

// ─── Search ─────────────────────────────────────────────────────────────────

/**
 * Type-ahead search across all connector operations.
 * Returns matching operations with provider name and description.
 */
export async function searchOperations(
  query: string,
  limit = 10
): Promise<SearchResult[]> {
  const manifest = await loadConnectorManifest();
  if (!manifest) return [];
  const defs = await getConnectorDefinitions();

  const results: SearchResult[] = [];
  const queryLower = query.toLowerCase();

  for (const [provider, entry] of Object.entries(manifest.connectors)) {
    const tierDef = defs[provider];
    const tier = tierDef?.tier ?? 3;

    for (const op of entry.operations) {
      const matchesName = op.name.toLowerCase().includes(queryLower);
      const matchesDesc = op.description.toLowerCase().includes(queryLower);
      const matchesProvider = provider.toLowerCase().includes(queryLower);

      if (matchesName || matchesDesc || matchesProvider) {
        results.push({
          provider,
          operation: op.name,
          description: op.description || `${provider}: ${op.name}`,
          tier,
        });
      }
    }
  }

  // Sort: tier 1 first, then by relevance
  results.sort((a, b) => {
    if (a.tier !== b.tier) return a.tier - b.tier;
    return 0;
  });

  return results.slice(0, limit);
}

// ─── Manifest → ConnectorDef Conversion ─────────────────────────────────────

/**
 * Convert manifest entries to the ConnectorDef format used by prompt.ts.
 * This allows using manifest data in the Genesis prompt builder.
 */
export function manifestToConnectorDefs(
  manifest: ConnectorManifest
): Record<string, ConnectorDef> {
  const defs: Record<string, ConnectorDef> = {};

  for (const [provider, entry] of Object.entries(manifest.connectors)) {
    // Use existing tier from hardcoded defs if available (sync fallback)
    const existing = _CONNECTOR_DEFINITIONS?.[provider];
    const tier = existing?.tier ?? 3;

    // Build full docs from manifest
    const fullDocs = buildProviderFullDocs(provider, entry);

    defs[provider] = {
      tier,
      full: tier <= 2 ? fullDocs : undefined,
      medium: tier === 2 ? fullDocs : undefined,
      stub: buildProviderStub(provider, entry),
      gapReference: existing?.gapReference,
    };
  }

  return defs;
}

/**
 * Build full operation documentation for a provider from manifest data.
 */
function buildProviderFullDocs(
  provider: string,
  entry: ConnectorManifestEntry
): string {
  const lines: string[] = [`${provider.toUpperCase()}:`];

  for (const op of entry.operations) {
    const params = op.parameters
      .filter((p) => p.name !== "self")
      .map((p) => `${p.name}?`)
      .join(", ");

    const paramStr = params ? `params={${params}}` : "";
    const desc = op.description ? ` — ${op.description}` : "";

    lines.push(`  ${op.name}: ${paramStr}${desc}`);
  }

  return lines.join("\n");
}

/**
 * Build a one-liner stub for a provider from manifest data.
 */
function buildProviderStub(
  provider: string,
  entry: ConnectorManifestEntry
): string {
  const ops = entry.operations.map((op) => op.name).join(", ");
  return `${provider.toUpperCase()}: ${ops}`;
}

// ─── Genesis Prompt Integration ─────────────────────────────────────────────

/**
 * Build the connector operations section for the Genesis system prompt
 * using manifest data. Falls back to hardcoded CONNECTOR_DEFINITIONS.
 */
export async function buildManifestAwareOperationsSection(
  selectedProviders?: string[] | null
): Promise<string> {
  const manifest = await loadConnectorManifest();

  if (!manifest) {
    // Fallback: use existing hardcoded definitions
    return buildHardcodedSection(selectedProviders);
  }

  return buildManifestSection(manifest, selectedProviders);
}

function buildHardcodedSection(selectedProviders?: string[] | null): string {
  const lines: string[] = ["OPERATION REFERENCE:\n"];
  const defs = _CONNECTOR_DEFINITIONS || {};

  if (!selectedProviders || selectedProviders.length === 0) {
    for (const [name, def] of Object.entries(defs)) {
      if (def.tier === 1 && def.full) {
        lines.push(def.full);
        lines.push("");
      }
    }
  } else {
    const selected = new Set(selectedProviders.map((p) => p.toLowerCase()));
    for (const [name, def] of Object.entries(defs)) {
      if (selected.has(name.toLowerCase())) {
        if (def.full) lines.push(def.full);
        else if (def.medium) lines.push(def.medium);
        else if (def.stub) lines.push(def.stub);
        lines.push("");
      }
    }
  }

  return lines.join("\n");
}

function buildManifestSection(
  manifest: ConnectorManifest,
  selectedProviders?: string[] | null
): string {
  const lines: string[] = ["OPERATION REFERENCE:\n"];
  const defs = _CONNECTOR_DEFINITIONS || {};

  const providers = selectedProviders
    ? selectedProviders.map((p) => p.toLowerCase())
    : Object.keys(manifest.connectors);

  for (const provider of providers) {
    const entry = manifest.connectors[provider];
    if (!entry) continue;

    const tierDef = defs[provider];
    const tier = tierDef?.tier ?? 3;

    if (tier <= 2) {
      lines.push(buildProviderFullDocs(provider, entry));
    } else {
      lines.push(buildProviderStub(provider, entry));
    }
    lines.push("");
  }

  return lines.join("\n");
}
