import Link from "next/link";
import type { Metadata } from "next";
import { LegalPageHeader } from "@/components/legal-page-header";

export const metadata: Metadata = {
  title: "Data Processing Agreement",
  description:
    "Corelyx Data Processing Agreement (DPA) for business customers under GDPR Article 28. Covers subject matter, processor obligations, sub-processor list, and data subject rights.",
  alternates: { canonical: "https://www.corelyx.app/dpa" },
  openGraph: { url: "https://www.corelyx.app/dpa" },
};

const LAST_UPDATED = "April 2026";

const clauses = [
  {
    title: "Parties and Scope",
    body:
      "This Data Processing Agreement forms part of the customer agreement between the customer as Controller and Corelyx as Processor. It applies when Corelyx processes personal data on behalf of a customer through the Corelyx workflow automation platform.",
  },
  {
    title: "Subject Matter, Duration, Nature, and Purpose",
    body:
      "The subject matter is processing personal data submitted to, generated by, or routed through customer-defined Corelyx workflows. Processing lasts for the term of the customer agreement plus the deletion or return period. The nature of processing includes collection, transmission, storage, retrieval, structuring, logging, deletion, and support access as needed to provide workflow automation, execution, approval gates, operational logging, support, security, and account administration.",
  },
  {
    title: "Data Subjects and Data Categories",
    body:
      "Data subjects may include platform users, customer employees, contractors, contacts, leads, support requesters, end customers, or other individuals contained in customer-configured workflows. Personal data may include names, email addresses, user IDs, account metadata, workflow payloads, CRM/contact fields, message metadata or content where configured, approval context, logs, and connector metadata. Special-category processing is not intended by default and requires customer-side legal assessment and safeguards.",
  },
  {
    title: "Processing Instructions",
    body:
      "Corelyx processes personal data only on documented customer instructions, including product configuration, workflow settings, the customer agreement, this DPA, and lawful written support requests. Corelyx will notify the customer if it believes an instruction infringes GDPR or applicable EU or Member State data protection law.",
  },
  {
    title: "Processor Obligations",
    body:
      "Corelyx will ensure authorized personnel are bound by confidentiality obligations, maintain appropriate technical and organizational measures, assist with data subject requests and DPIAs where reasonably required, and delete or return personal data after termination according to the deletion and return clause.",
  },
  {
    title: "Controller Obligations",
    body:
      "The customer remains responsible for maintaining a valid legal basis, configuring workflows lawfully, providing required notices to data subjects, avoiding unnecessary personal data or secrets in prompts and logs, and conducting DPIAs where required for high-risk workflows.",
  },
  {
    title: "Security Measures",
    body:
      "Corelyx maintains measures aligned with GDPR Article 32, including encryption in transit, encrypted infrastructure and secret storage, server-side credential handling, owner-scoped access controls, human approval gates, audit logging, retention jobs, vulnerability disclosure, dependency scanning, SAST, and incident response procedures.",
  },
  {
    title: "Subprocessors",
    body:
      "Corelyx may use subprocessors listed in the public subprocessor registry. Corelyx will impose materially equivalent data protection obligations on subprocessors and remains responsible for their performance. The public registry is available at /subprocessors.",
  },
  {
    title: "Subprocessor Change Notice",
    body:
      "Corelyx will provide at least 30 days' advance notice before adding or replacing a subprocessor that processes customer personal data, unless urgent security, availability, or legal requirements make advance notice impracticable. Customers may object on reasonable data protection grounds before the change takes effect.",
  },
  {
    title: "International Transfers and EU Data Residency",
    body:
      "Corelyx uses EU-first infrastructure and provides EU-only controls for eligible workflows. EU-only mode can restrict storage, logs, model providers, and workflow execution to approved EU/EEA infrastructure, but customer-selected integrations, model providers, email providers, analytics tools, billing providers, or account-level provider settings may still involve processing outside the EEA. Transfers outside the EEA require a lawful transfer mechanism such as Standard Contractual Clauses, an adequacy decision, or another GDPR Chapter V mechanism. LLM providers or subprocessors outside the EEA must have appropriate DPA/SCC coverage before production use with customer personal data.",
  },
  {
    title: "Deletion and Return",
    body:
      "Upon termination or written customer instruction, Corelyx will delete or return customer personal data within 30 days unless EU or Member State law requires retention. Deletion may occur through product self-service deletion, account deletion, database cascade deletion, Vault secret deletion, and subprocessor deletion requests or account cancellation where supported. Backup copies may persist until overwritten by normal backup rotation and remain protected during that period.",
  },
  {
    title: "Data Subject Requests",
    body:
      "Corelyx assists with data subject requests by providing account and workflow data export, machine-readable portability export, account deletion mechanisms, processing restriction flags, and audit records of submitted requests. The customer remains responsible for verifying identity and deciding the legally appropriate response where it determines the purpose and means of processing.",
  },
  {
    title: "Personal Data Breach Notification",
    body:
      "Corelyx will notify the customer without undue delay and, where feasible, within 24 hours after becoming aware of a personal data breach affecting customer personal data. The notice will include available information about the breach nature, affected data subjects and records, likely consequences, measures taken or proposed, and the Corelyx contact point.",
  },
  {
    title: "Audit Rights",
    body:
      "Upon reasonable written request, Corelyx will provide information necessary to demonstrate compliance, such as security policy, subprocessor registry, incident response policy, retention documentation, and relevant third-party audit reports if available. On-site or invasive audits require reasonable notice, confidentiality protections, scope limitations, and safeguards for other customers' data and Corelyx security.",
  },
  {
    title: "DPIAs and Prior Consultation",
    body:
      "Corelyx will provide reasonable assistance for DPIAs and supervisory-authority consultations where the assistance relates to processing performed by Corelyx and the customer cannot reasonably obtain the information itself.",
  },
];

export default async function DpaPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <LegalPageHeader maxWidthClass="max-w-4xl" />

      <main className="relative mx-auto max-w-4xl px-6 py-16">
        <div className="mb-10">
          <p className="mb-3 text-[10px] font-bold uppercase tracking-[0.2em] text-primary">
            Legal
          </p>
          <h1 className="text-4xl font-black tracking-tight sm:text-5xl">
            Data Processing Agreement
          </h1>
          <p className="mt-4 text-sm text-muted-foreground">
            For business customers. Last updated: {LAST_UPDATED}.
          </p>
        </div>

        <div className="space-y-5">
          {clauses.map((clause, index) => (
            <section key={clause.title} className="rounded-2xl border border-border bg-card/60 p-5">
              <h2 className="text-base font-semibold text-foreground">
                {index + 1}. {clause.title}
              </h2>
              <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                {clause.body}
              </p>
            </section>
          ))}
        </div>
      </main>

      <footer className="border-t border-border/40 px-6 py-6">
        <div className="mx-auto flex max-w-4xl items-center gap-5 text-xs text-muted-foreground/60">
          <Link href="/privacy" className="hover:text-foreground">Privacy</Link>
          <Link href="/terms" className="hover:text-foreground">Terms</Link>
          <Link href="/subprocessors" className="hover:text-foreground">Subprocessors</Link>
        </div>
      </footer>
    </div>
  );
}
