// Corelyx Schema Codegen (Task #5: Type-Safe Schema Registry + Codegen, Score 8.0)
// Schritt 1-2: Extract canonical JSON Schema from Zod validators and emit a
// generated schema.json + TypeScript types artifact.
//
// Run: pnpm --filter @flowos/schema codegen
// Output: packages/schema/generated/schema.json, packages/schema/generated/types.ts
//
// Phase 2 (Schritt 3): feed schema.json to `datamodel-code-generator` to emit
// apps/runtime/generated/models.py. See apps/runtime/requirements.txt note.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { zodToJsonSchema } from "zod-to-json-schema";
import * as validators from "../src/validators";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(__dirname, "../generated");

mkdirSync(OUT_DIR, { recursive: true });

// Collect every exported Zod schema from validators.ts
const schema: Record<string, unknown> = { $schema: "http://json-schema.org/draft-07/schema#", definitions: {} };
for (const [name, def] of Object.entries(validators)) {
  if (def && typeof def === "object" && "parse" in def && "_def" in def) {
    // @ts-expect-error zod schema structural check
    schema.definitions[name] = zodToJsonSchema(def, { $refStrategy: "none" });
  }
}

const schemaJson = JSON.stringify(schema, null, 2) + "\n";
writeFileSync(resolve(OUT_DIR, "schema.json"), schemaJson);

// Explicit TS types artifact (re-export of inferred types for downstream consumers)
const typesTs = `// AUTO-GENERATED by scripts/codegen.ts — do not edit by hand.\n` +
  `export type { ProgramSchema, NodeSchema, EdgeSchema } from "../src/validators";\n` +
  `export const schemaJson = ${JSON.stringify(schema)} as const;\n`;
writeFileSync(resolve(OUT_DIR, "types.ts"), typesTs);

console.log(`[codegen] wrote ${Object.keys(schema.definitions).length} definitions to generated/`);
