apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "corelyx.fullname" . }}-config
  labels:
    {{- include "corelyx.labels" . | nindent 4 }}
data:
  NODE_ENV: production
  NEXT_PUBLIC_APP_URL: {{ .Values.config.appUrl | quote }}
  NEXT_PUBLIC_RUNTIME_URL: {{ .Values.config.runtimeUrl | quote }}
  NEXT_PUBLIC_SUPABASE_URL: {{ .Values.config.supabaseUrl | quote }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: {{ .Values.config.supabaseAnonKey | quote }}
  NEXT_PUBLIC_SENTRY_TRACE_SAMPLE_RATE: {{ .Values.config.sentryTraceSampleRate | quote }}
