{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "corelyx.serviceAccountName" . }}
  labels:
    {{- include "corelyx.labels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "corelyx.fullname" . }}-web
  labels:
    {{- include "corelyx.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "corelyx.web.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "corelyx.fullname" . }}-runtime
  labels:
    {{- include "corelyx.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "corelyx.runtime.selectorLabels" . | nindent 6 }}
{{- end }}
